### ISSUE TITLE
Issue compiling libjit on Ubuntu Trusty

### ISSUE THREAD

**Issue by snim2** [gergo-/pylibjit#1]
This is the result of running `make` after installing `libtool`, re-running `libjit/auto_gen.sh` and running `libjit/configure`:

```
$ make

make  all-recursive

make[1]: Entering directory `.../pylibjit/libjit'

Making all in tools

make[2]: Entering directory `.../pylibjit/libjit/tools'

make  all-am

make[3]: Entering directory `.../pylibjit/libjit/tools'

make[3]: Nothing to be done for `all-am'.

make[3]: Leaving directory `.../pylibjit/libjit/tools'

make[2]: Leaving directory `.../pylibjit/libjit/tools'

Making all in include

make[2]: Entering directory `.../pylibjit/libjit/include'

Making all in jit

make[3]: Entering directory `.../pylibjit/libjit/include/jit'

make  all-am

make[4]: Entering directory `.../pylibjit/libjit/include/jit'

make[4]: Nothing to be done for `all-am'.

make[4]: Leaving directory `.../pylibjit/libjit/include/jit'

make[3]: Leaving directory `.../pylibjit/libjit/include/jit'

make[3]: Entering directory `.../pylibjit/libjit/include'

make[3]: Nothing to be done for `all-am'.

make[3]: Leaving directory `.../pylibjit/libjit/include'

make[2]: Leaving directory `.../pylibjit/libjit/include'

Making all in jit

make[2]: Entering directory `.../pylibjit/libjit/jit'

make  all-am

make[3]: Entering directory `.../pylibjit/libjit/jit'

make[3]: Nothing to be done for `all-am'.

make[3]: Leaving directory `.../pylibjit/libjit/jit'

make[2]: Leaving directory `.../pylibjit/libjit/jit'

Making all in jitdynamic

make[2]: Entering directory `.../pylibjit/libjit/jitdynamic'

make[2]: Nothing to be done for `all'.

make[2]: Leaving directory `.../pylibjit/libjit/jitdynamic'

Making all in jitplus

make[2]: Entering directory `.../pylibjit/libjit/jitplus'

make[2]: Nothing to be done for `all'.

make[2]: Leaving directory `.../pylibjit/libjit/jitplus'

Making all in dpas

make[2]: Entering directory `.../pylibjit/libjit/dpas'

make[2]: Nothing to be done for `all'.

make[2]: Leaving directory `.../pylibjit/libjit/dpas'

Making all in tutorial

make[2]: Entering directory `.../pylibjit/libjit/tutorial'

make[2]: Nothing to be done for `all'.

make[2]: Leaving directory `.../pylibjit/libjit/tutorial'

Making all in tests

make[2]: Entering directory `.../pylibjit/libjit/tests'

make[2]: Nothing to be done for `all'.

make[2]: Leaving directory `.../pylibjit/libjit/tests'

Making all in doc

make[2]: Entering directory `.../pylibjit/libjit/doc'

restore=: && backupdir=".am$$" && \
am__cwd=`pwd` && CDPATH="${ZSH_VERSION+.}:" && cd . && \
rm -rf $backupdir && mkdir $backupdir && \
if (/bin/bash .../pylibjit/libjit/build-aux/missing makeinfo --version) >/dev/null 2>&1; then \
  for f in libjit.info libjit.info-[0-9] libjit.info-[0-9][0-9] libjit.i[0-9] libjit.i[0-9][0-9]; do \
    if test -f $f; then mv $f $backupdir; restore=mv; else :; fi; \
  done; \
else :; fi && \
cd "$am__cwd"; \
if /bin/bash .../pylibjit/libjit/build-aux/missing makeinfo   -I . \
 -o libjit.info libjit.texi; \
then \
  rc=0; \
  CDPATH="${ZSH_VERSION+.}:" && cd .; \
else \
  rc=$?; \
  CDPATH="${ZSH_VERSION+.}:" && cd . && \
  $restore $backupdir/* `echo "./libjit.info" | sed 's|[^/]*$||'`; \
fi; \
rm -rf $backupdir; exit $rc

libjit.texi:26: misplaced {

libjit.texi:26: misplaced }

make[2]: *** [libjit.info] Error 1

make[2]: Leaving directory `.../pylibjit/libjit/doc'

make[1]: *** [all-recursive] Error 1

make[1]: Leaving directory `.../pylibjit/libjit'

make: *** [all] Error 2

$
```

**Comment by gergo-** [comment]
Thanks for the report. Looks like you have a newer version of texinfo, which changed the syntax it will accept. This should be fixed now, please let me know if the current version works for you.

**Comment by snim2** [comment]
Thanks, that works, but once `libjit` is installed and `libjit-python` has been built and installed with python3 I get this from the root directory of the project:

```
$ python3 setup.py build
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import pylibjit
  File "/home/snim2/Desktop/working/pylibjit/pylibjit/__init__.py", line 1, in <module>
    from .bc_compiler import compile, this_class
  File "/home/snim2/Desktop/working/pylibjit/pylibjit/bc_compiler.py", line 2, in <module>
    import jit
ImportError: libjit.so.0: cannot open shared object file: No such file or directory
```

**Comment by gergo-** [comment]
If you didn't install libjit in /usr/local, you'll have to tell the dynamic linker where it lives. Try setting
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/libjit/lib/
and/or (as root) editing something like /etc/ld.so.conf and running ldconfig.

**Comment by snim2** [comment]
Hmm. I used the default values for paths:

```
$ ls /usr/local/lib/libjit*
/usr/local/lib/libjit.a          /usr/local/lib/libjitdynamic.so.0      
/usr/local/lib/libjitplus.la        /usr/local/lib/libjit.so
/usr/local/lib/libjitdynamic.a   /usr/local/lib/libjitdynamic.so.0.0.1  
/usr/local/lib/libjitplus.so        /usr/local/lib/libjit.so.0
/usr/local/lib/libjitdynamic.la  /usr/local/lib/libjit.la               
/usr/local/lib/libjitplus.so.0      /usr/local/lib/libjit.so.0.0.1
/usr/local/lib/libjitdynamic.so  /usr/local/lib/libjitplus.a           
 /usr/local/lib/libjitplus.so.0.0.1
```

**Comment by gergo-** [comment]
OK, weird. And probably difficult to debug remotely :-( I can hint at two things to try.
1. Run `ldconfig -p | grep libjit`, which should output paths to the `.so` files you listed above. If it doesn't, you will have to run `ldconfig` in the correct way to rebuild its cache to include those libraries in `/usr/local/lib`. I think.
2. Run something like `ldd /usr/local/lib/python3.2/dist-packages/jit.cpython-32mu.so` (possibly adjusting 3.2 to your Python's major.minor version number). This is the `.so` built and installed by libjit-python. The output of `ldd` should show that all references to other libraries are resolved correctly. On my machine:

> ~/pylibjit/libjit-python$ ldd /usr/local/lib/python3.2/dist-packages/jit.cpython-32mu.so 
>   linux-gate.so.1 =>  (0x00939000)
>   libjit.so.0 => /usr/local/lib/libjit.so.0 (0x006c1000)
>   libjitplus.so.0 => /usr/local/lib/libjitplus.so.0 (0x0024f000)
>   libjitdynamic.so.0 => /usr/local/lib/libjitdynamic.so.0 (0x00691000)
>   libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0x00984000)
>   ...

If this doesn't find `libjit.so.0` and the others, then again you will have to find out how to get your dynamic linker to look in all the right places. Maybe.

**Comment by snim2** [comment]
`ldconfig` looks fine and finds all the files. The file `jit.cpython-32mu.so` did not exist and could not be found by `locate`, so I rebuilt and reinstalled the `libjit-python` wrapper and that seemed to fix everything. No idea why, maybe user error?! Thanks for fixing the original issue.

**Comment by gergo-** [comment]
Strange. Glad it seems to work now, have fun :-)
